name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spiceai/helm-charts
        uses: actions/checkout@v4
        with:
          path: helm-charts
          fetch-depth: 0

      - name: Checkout spiceai/spiceai
        uses: actions/checkout@v4
        with:
          path: spiceai
          repository: spiceai/spiceai
          fetch-depth: 0

      - name: Configure Git
        working-directory: helm-charts
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install chart-releaser
        uses: ./helm-charts/.github/actions/chart-releaser-installer
      
      - name: Release Charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr version
          cr package spiceai/deploy/chart
          cd helm-charts
          cr upload --owner spiceai --git-repo helm-charts --packages-with-index --token $CR_TOKEN --push --skip-existing
          cr index --owner spiceai --git-repo helm-charts  --packages-with-index --index-path . --token <token> --push