name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spiceai/helm-charts
        uses: actions/checkout@v4
        with:
          path: helm-charts
          fetch-depth: 0

      - name: Checkout spiceai/spiceai
        uses: actions/checkout@v4
        with:
          path: spiceai
          repository: spiceai/spiceai
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: ./helm-charts/.github/actions/chart-releaser-action
        with:
          charts_dir: spiceai/deploy
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"